"""State initialization — populates state files with initial data.

Run once before first deployment to ensure all state files exist
with valid initial data. Idempotent — safe to run multiple times.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from claw_quant.config import (
    PROJECT_ROOT,
    FISHER_STATE_PATH,
    SFM_STATE_PATH,
    DAMODARAN_STATE_PATH,
    CAPITAL_ALLOCATION_REGISTRY_PATH,
    DATA_PROVIDER,
)

logger = logging.getLogger("claw_quant.state_init")


def init_all() -> dict[str, bool]:
    """Initialize all state files. Returns status per file."""
    results = {}

    results["fisher"] = init_fisher_state()
    results["sfm"] = init_sfm_state()
    results["damodaran"] = init_damodaran_state()
    results["capital"] = init_capital_registry()
    results["directories"] = init_directories()

    success = all(results.values())
    logger.info(
        "State initialization: %s (%d/%d files OK)",
        "SUCCESS" if success else "PARTIAL",
        sum(results.values()),
        len(results),
    )
    return results


def init_fisher_state() -> bool:
    """Initialize fisher_state.md with default structure.

    The Fisher layer will be populated with real data on first refresh.
    This creates the file with the correct schema and default values.
    """
    if FISHER_STATE_PATH.exists():
        logger.info("Fisher state already exists: %s", FISHER_STATE_PATH)
        return True

    content = f"""# Fisher Layer State — Monetary Environment

<!-- Auto-generated by state_init.py -->
<!-- Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -->
<!-- Schema: ADR-011 (Mundell-Fleming / Rey framework) -->

## Layer 1: Global Financial Cycle

```yaml
global_financial_cycle:
  fed_balance_sheet:
    status: monitoring
    trend: unknown
    note: "Awaiting first data refresh"
  fed_rate:
    current: unknown
    market_implied_path: unknown
    cycle_phase: unknown
  usd_purchasing_power:
    trend: unknown
    cpi_latest: unknown
```

## Layer 2: Transmission Channels

```yaml
transmission_channels:
  cross_border_portfolio:
    signal_strength: unknown
    marginal_contribution: 0.35
    status: monitoring
    northbound_5d: 0
    northbound_trend: unknown
  fx_reserves:
    signal_strength: unknown
    marginal_contribution: 0.10
    pboc_balance_sheet: unknown
    status: monitoring
  risk_discount:
    signal_strength: unknown
    marginal_contribution: 0.15
    ust_10y: unknown
    vix: unknown
    status: monitoring
```

## Layer 3: A-Share Marginal Liquidity

```yaml
a_share_marginal_liquidity:
  composite_signal: unknown
  pboc_modifier: neutral
  equity_transmission_efficiency: 0.10
  margin_balance: 0
  margin_trend: unknown
  sfisf_status: inactive
```

## Layer 4: Composite Assessment

```yaml
composite_assessment:
  fed_cycle_phase: unknown
  bull_market_conditions_met: false
  stock_vs_cash_baseline: neutral
  position_constraint:
    max_aggregate_equity: 0.60
  confidence: 0.50
  signal_1: "Awaiting first data refresh"
  signal_2: "Awaiting first data refresh"
```

## Fisher Interface (Graham Contract)

```yaml
fisher_interface:
  phase: neutral
  stock_vs_cash: neutral
  key_signal_1: "awaiting_data"
  key_signal_2: "awaiting_data"
  position_constraint: "max_equity: 0.60"
  confidence: 0.50
  data_freshness: never
  last_updated: null
```

## Regime Surveillance Log

```yaml
regime_surveillance_log: []
```
"""
    FISHER_STATE_PATH.write_text(content, encoding="utf-8")
    logger.info("Created fisher_state.md")
    return True


def init_sfm_state() -> bool:
    """Initialize sfm_state.md with default structure.

    The SFM state will be populated with real data when the weekly
    scripts run. This creates the file with the correct schema.
    """
    if SFM_STATE_PATH.exists():
        logger.info("SFM state already exists: %s", SFM_STATE_PATH)
        return True

    content = f"""# SFM Layer State — Factor Manifold

<!-- Auto-generated by state_init.py -->
<!-- Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -->
<!-- Schema: ADR-014 (Sharpe-Fama-Merton manifold state) -->

## Module 1a: Carhart Baseline

```yaml
carhart_baseline:
  status: pending
  note: "Awaiting first weekly Carhart regression run"
```

## Module 1b: Factor Duration Spectrum

```yaml
factor_duration_spectrum:
  status: pending
  short_term: {{}}
  medium_term: {{}}
  long_term: {{}}
```

## Module 1c: Extended Premia

```yaml
extended_premia:
  status: pending
  note: "Awaiting first options proxy run"
```

## Module 2a: Crowding by Duration

```yaml
crowding_by_duration:
  status: pending
  note: "Awaiting first crowding update"
```

## Module 2b: Institutional Constraints

```yaml
institutional_constraints:
  status: pending
```

## Module 2c: Transient Anomaly

```yaml
transient_anomaly:
  status: pending
```

## Module 3a: Duration Regime

```yaml
duration_regime:
  dominant_bucket: unknown
  confidence: 0.0
```

## Module 3b: Forced Movement

```yaml
forced_movement:
  cffex_signal: pending
  momentum_crash_preconditions:
    market_decline: unknown
    high_volatility: unknown
    market_rebound: unknown
```

## Module 3c: Rotation Path

```yaml
rotation_path:
  current_state: unknown
  target_state: unknown
  friction: unknown
```

## Module 4: Composite Output

```yaml
composite_output:
  manifold_state: unknown
  factor_preference: {{}}
  environment_constraints: {{}}
```

## SFM Interface (Graham Contract)

```yaml
sfm_interface:
  phase: neutral
  preferred_factors: []
  key_signal_1: "awaiting_data"
  key_signal_2: "awaiting_data"
  gradient_direction: stable
  confidence: 0.50
  data_freshness: never
  last_updated: null
```
"""
    SFM_STATE_PATH.write_text(content, encoding="utf-8")
    logger.info("Created sfm_state.md")
    return True


def init_damodaran_state() -> bool:
    """Initialize damodaran_state.md if it doesn't exist."""
    if DAMODARAN_STATE_PATH.exists():
        logger.info("Damodaran state already exists: %s", DAMODARAN_STATE_PATH)
        return True

    DAMODARAN_STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = f"""# Damodaran Cross-Section Supervisor State

<!-- Auto-generated by state_init.py -->
<!-- Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -->

## Belief Pool

```yaml
belief_pool:
  total_active_theses: 0
  max_recommended: 5
  theses_summary: []
  belief_diversity:
    by_type: {{}}
    by_duration: {{}}
    by_factor_exposure: {{}}
```

## Holdings Pool

```yaml
holdings_pool:
  total_unique_tickers: 0
  max_recommended: 15
  ticker_overlap: []
  aggregate_exposure:
    total_equity: 0.0
    total_cash: 1.0
    total_by_sector: {{}}
```

## Constraints

```yaml
constraints:
  - name: max_active_theses
    limit: 5
    current: 0
    status: within_limit
  - name: max_unique_tickers
    limit: 15
    current: 0
    status: within_limit
  - name: max_single_thesis_weight
    limit: 0.40
    current: 0.0
    status: within_limit
  - name: max_single_ticker_weight
    limit: 0.15
    current: 0.0
    status: within_limit
  - name: max_single_duration_bucket
    limit: 0.60
    current: 0.0
    status: within_limit
  - name: max_single_sector
    limit: 0.50
    current: 0.0
    status: within_limit
  - name: fisher_max_aggregate_equity
    limit: 0.80
    current: 0.0
    status: within_limit
```

## Forward Valuation

```yaml
forward_valuation:
  per_thesis_forward: []
  total_current_value: 0
  total_forward_intrinsic: 0
  aggregate_forward_return: 0.0
  confidence_weighted_aggregate: 0.0
  backward_pnl:
    realized: 0
    unrealized: 0
    note: "Reference only"
```
"""
    DAMODARAN_STATE_PATH.write_text(content, encoding="utf-8")
    logger.info("Created damodaran_state.md")
    return True


def init_capital_registry() -> bool:
    """Initialize capital_allocation_registry.md if it doesn't exist."""
    if CAPITAL_ALLOCATION_REGISTRY_PATH.exists():
        logger.info("Capital allocation registry already exists: %s", CAPITAL_ALLOCATION_REGISTRY_PATH)
        return True

    CAPITAL_ALLOCATION_REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = f"""# Capital Allocation Registry

<!-- Auto-generated by state_init.py -->
<!-- Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -->

```yaml
total_capital: 1000000
fisher_max_aggregate_equity: 0.60
active_theses: []
available_capital: 1000000
aggregate_equity_exposure: 0.0
aggregate_cash_exposure: 1.0
```
"""
    CAPITAL_ALLOCATION_REGISTRY_PATH.write_text(content, encoding="utf-8")
    logger.info("Created capital_allocation_registry.md")
    return True


def init_directories() -> bool:
    """Ensure all required directories exist."""
    dirs = [
        PROJECT_ROOT / "theses",
        PROJECT_ROOT / "holdings",
        PROJECT_ROOT / "portfolio",
        PROJECT_ROOT / "data",
        PROJECT_ROOT / "data" / "fisher_snapshots",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    logger.info("Directories OK")
    return True


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    results = init_all()
    for name, ok in results.items():
        print(f"  {'✅' if ok else '❌'} {name}")
    print(f"\nData provider: {DATA_PROVIDER}")
    print("Run 'python3 -m claw_quant.agent_interface --weekly' to populate with real data.")